var THEMES = [
  {
    id: 'petalpop',
    name: 'PetalPop Parade',
    tagline: 'Spring-bright, buoyant, blooming',
    icon: '✿',
    tokens: {
      '--bg':             '#FFF5F8',
      '--bg-warm':        '#FFF0F5',
      '--cream':          '#FFF3F0',
      '--rose':           '#FF6B9D',
      '--rose-light':     '#FFACC7',
      '--rose-mid':       '#FF87B2',
      '--rose-dark':      '#C94080',
      '--gold':           '#FF8C42',
      '--gold-light':     '#FFD080',
      '--text':           '#3D1040',
      '--text-soft':      '#7A4060',
      '--crescendo-dark': '#4A0024',
      '--crescendo-mid':  '#C94080',
      '--orb-shadow':     'rgba(255,107,157,0.40)',
      '--selector-bg-a':  '#FFD4EE',
      '--ph-bg-start':    '#FFE4F0',
      '--ph-bg-end':      '#FFBBD5',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#FFACC7', '--petal-2': '#FF87B2',
      '--petal-3': '#FFD0E0', '--petal-4': '#FFBBD5',
      '--petal-5': '#FFC0CC', '--petal-6': '#FF97B8'
    }
  },
  {
    id: 'moonlight-mithai',
    name: 'Moonlight Mithai',
    tagline: 'Dreamy, luminous, silver-soft',
    icon: '☽',
    tokens: {
      '--bg':             '#F4F0FF',
      '--bg-warm':        '#EEE8FF',
      '--cream':          '#F8F4FF',
      '--rose':           '#8B7DD4',
      '--rose-light':     '#BAB4E8',
      '--rose-mid':       '#9B8ED9',
      '--rose-dark':      '#5E4FA8',
      '--gold':           '#C9AD60',
      '--gold-light':     '#E8D090',
      '--text':           '#2A1F4A',
      '--text-soft':      '#5A4A80',
      '--crescendo-dark': '#0A0418',
      '--crescendo-mid':  '#3B2880',
      '--orb-shadow':     'rgba(139,125,212,0.40)',
      '--selector-bg-a':  '#D8D0FF',
      '--ph-bg-start':    '#E8E0FF',
      '--ph-bg-end':      '#C4B5F4',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#C4B5F4', '--petal-2': '#A78BFA',
      '--petal-3': '#DDD6FE', '--petal-4': '#B4A8E8',
      '--petal-5': '#C9C0F0', '--petal-6': '#9A8ED4'
    }
  },
  {
    id: 'candy-cloud',
    name: 'CandyCloud Caravan',
    tagline: 'Pastel-bright, bouncy, sweet',
    icon: '☁',
    tokens: {
      '--bg':             '#FFF5FC',
      '--bg-warm':        '#FFF0FA',
      '--cream':          '#FFF8F5',
      '--rose':           '#FF85C1',
      '--rose-light':     '#FFADD6',
      '--rose-mid':       '#FF9BCE',
      '--rose-dark':      '#D45A90',
      '--gold':           '#FFD166',
      '--gold-light':     '#FFE8A0',
      '--text':           '#3D1030',
      '--text-soft':      '#7A3060',
      '--crescendo-dark': '#4A0040',
      '--crescendo-mid':  '#B035A0',
      '--orb-shadow':     'rgba(255,133,193,0.40)',
      '--selector-bg-a':  '#FFD4EE',
      '--ph-bg-start':    '#FFE0F5',
      '--ph-bg-end':      '#FFADD6',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#FFADD6', '--petal-2': '#A8E6CF',
      '--petal-3': '#FFD166', '--petal-4': '#FF9BCE',
      '--petal-5': '#C4B5F4', '--petal-6': '#FFCBA4'
    }
  },
  {
    id: 'gulabo-garden',
    name: 'Gulabo Garden Gala',
    tagline: 'Marigold-bright, festive, radiant',
    icon: '❀',
    tokens: {
      '--bg':             '#FFF3EE',
      '--bg-warm':        '#FFEDE4',
      '--cream':          '#FFF5EE',
      '--rose':           '#D42B2B',
      '--rose-light':     '#F08080',
      '--rose-mid':       '#E05050',
      '--rose-dark':      '#9B1010',
      '--gold':           '#F4900C',
      '--gold-light':     '#FDBA60',
      '--text':           '#3A1000',
      '--text-soft':      '#7A3000',
      '--crescendo-dark': '#3A0000',
      '--crescendo-mid':  '#8B1C1C',
      '--orb-shadow':     'rgba(212,43,43,0.40)',
      '--selector-bg-a':  '#FFD4C0',
      '--ph-bg-start':    '#FFE0D0',
      '--ph-bg-end':      '#F08080',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#F08080', '--petal-2': '#FDBA60',
      '--petal-3': '#F4900C', '--petal-4': '#E05050',
      '--petal-5': '#FFD07A', '--petal-6': '#FF8060'
    }
  },
  {
    id: 'starry-snuggle',
    name: 'Starry Snuggle Story',
    tagline: 'Violet-deep, starlit, intimate',
    icon: '✦',
    tokens: {
      '--bg':             '#F5F3FF',
      '--bg-warm':        '#F0EEFF',
      '--cream':          '#F8F6FF',
      '--rose':           '#7C3AED',
      '--rose-light':     '#A78BFA',
      '--rose-mid':       '#8B5CF6',
      '--rose-dark':      '#5B21B6',
      '--gold':           '#D4B896',
      '--gold-light':     '#EED8B4',
      '--text':           '#1A0A3A',
      '--text-soft':      '#4A3070',
      '--crescendo-dark': '#0A041C',
      '--crescendo-mid':  '#2D1B6B',
      '--orb-shadow':     'rgba(124,58,237,0.40)',
      '--selector-bg-a':  '#DDD6FE',
      '--ph-bg-start':    '#EAE4FF',
      '--ph-bg-end':      '#C4B5F4',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#A78BFA', '--petal-2': '#818CF8',
      '--petal-3': '#C4B5F4', '--petal-4': '#8B5CF6',
      '--petal-5': '#DDD6FE', '--petal-6': '#9A8ED4'
    }
  },
  {
    id: 'butterfly-blush',
    name: 'ButterflyBlush Bash',
    tagline: 'Mint-fresh, airy, full of flutter',
    icon: '❋',
    tokens: {
      '--bg':             '#F5FFF8',
      '--bg-warm':        '#F0FFF5',
      '--cream':          '#FAFFFC',
      '--rose':           '#E879A0',
      '--rose-light':     '#F4A8C0',
      '--rose-mid':       '#EE8CB0',
      '--rose-dark':      '#B85080',
      '--gold':           '#68D391',
      '--gold-light':     '#98EFBA',
      '--text':           '#1A2E20',
      '--text-soft':      '#406050',
      '--crescendo-dark': '#1A001C',
      '--crescendo-mid':  '#6B1080',
      '--orb-shadow':     'rgba(232,121,160,0.40)',
      '--selector-bg-a':  '#C8F0D8',
      '--ph-bg-start':    '#E0FFF0',
      '--ph-bg-end':      '#F4A8C0',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#F4A8C0', '--petal-2': '#98EFBA',
      '--petal-3': '#C4B5F4', '--petal-4': '#EE8CB0',
      '--petal-5': '#A0E8C0', '--petal-6': '#F0B8D0'
    }
  },
  {
    id: 'sangeetspark',
    name: 'SangeetSpark Symphony',
    tagline: 'Gold-blazing, festive, electric',
    icon: '✺',
    tokens: {
      '--bg':             '#1A0A00',
      '--bg-warm':        '#220D00',
      '--cream':          '#2A1200',
      '--rose':           '#F59E0B',
      '--rose-light':     '#FCD34D',
      '--rose-mid':       '#FBBF24',
      '--rose-dark':      '#D97706',
      '--gold':           '#FDE68A',
      '--gold-light':     '#FFFBEB',
      '--brown':          '#FDF3E3',
      '--text':           '#FDF3E3',
      '--text-soft':      '#FBD5A0',
      '--crescendo-dark': '#0A0400',
      '--crescendo-mid':  '#5C1A00',
      '--orb-shadow':     'rgba(245,158,11,0.50)',
      '--selector-bg-a':  '#3A1800',
      '--ph-bg-start':    '#2A1000',
      '--ph-bg-end':      '#4A2000',
      '--ts-start-bg':    'rgba(255,255,255,0.12)',
      '--petal-1': '#FCD34D', '--petal-2': '#F59E0B',
      '--petal-3': '#FBBF24', '--petal-4': '#D97706',
      '--petal-5': '#FDE68A', '--petal-6': '#F97316'
    }
  },
  {
    id: 'velvet-vows',
    name: 'VelvetVows Voyage',
    tagline: 'Plum-rich, cinematic, timeless',
    icon: '❖',
    tokens: {
      '--bg':             '#FDF8FF',
      '--bg-warm':        '#F8F0FF',
      '--cream':          '#FFF5FF',
      '--rose':           '#9D174D',
      '--rose-light':     '#C869A0',
      '--rose-mid':       '#B04080',
      '--rose-dark':      '#6D0A38',
      '--gold':           '#C4956A',
      '--gold-light':     '#E8C8A0',
      '--text':           '#2A0A20',
      '--text-soft':      '#6A3050',
      '--crescendo-dark': '#0D0014',
      '--crescendo-mid':  '#5B0A5B',
      '--orb-shadow':     'rgba(157,23,77,0.40)',
      '--selector-bg-a':  '#E8C8F0',
      '--ph-bg-start':    '#F0E0FF',
      '--ph-bg-end':      '#C869A0',
      '--ts-start-bg':    'rgba(255,255,255,0.65)',
      '--petal-1': '#C869A0', '--petal-2': '#B04080',
      '--petal-3': '#E8C8A0', '--petal-4': '#D4A0C0',
      '--petal-5': '#F0D0E0', '--petal-6': '#C890B0'
    }
  }
];
